#!/usr/bin/env bash
# setup and run nginx server

apt-get update -y

if ! apt-get install -y nginx;
then
	echo "Failed to install nginx" 1>&2
	exit 1
fi

line="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=dQw4w9WgXcQ permanent;"
sudo sed -i "26i $line" /etc/nginx/sites-available/default
echo "Holberton School" > /var/www/html/index.html

if ! service nginx restart;
then
	echo "Failed to start nginx" 1>&2
	exit 1
fi

exit 0
