#!/usr/bin/env bash
# Install HAproxy on clean ubuntu 14.04 machine and setup to proxy requests
# shellcheck disable=SC2016

apt-get update -y

apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0

apt-get install -y haproxy=2.0.\*

echo "ENABLED=1" >> /etc/default/haproxy

echo "
frontend load_balancer
    bind *:80
    mode http
    default_backend webserver
backend webserver
    balance roundrobin
    server 2244-web-01 35.196.157.89:80 check
    server 2244-web-02 104.196.22.43:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy restart
