#!/usr/bin/env bash
# Display list of currently running processes with process hierarchy
# shellcheck disable=SC2009

ps -eo user,pid,%cpu,%mem,vsz,rss,tname,stat,start_time,bsdtime,args --forest |\
grep bash
