#!/usr/bin/env bash
#display hours from 0 to 12 and
#display minutes from 1 to 59

hour=0

while [ $hour -le 12 ]
do
	echo Hour: $hour
	min=1
	while [ $min -le 59 ]
	do
		echo $min
		min=$((min+1))
	done
	hour=$((hour+1))
done
